project:
  type: website

website:
  # --- CHANGED: Updated title and description for better OG data ---
  title: "🤍 One Signal: Music. Soul. Love."
  description: "This is more than a record label; it is a sanctuary. In a world of noise, our mission is to 'shrink the data' - to find the essential, healing frequencies that reconnect you to your heart. Music is chosen with intent."
  image: images/tds-logo-150px.png
  favicon: images/tds-favicon.png
  twitter-card:
    site: "@thedatashrink"
  open-graph: true
  site-url: https://www.thedoctorshrink.com/
  repo-url: https://github.com/Doctorshrink/Doctorshrink.github.io
  repo-actions: [edit, issue]
  navbar:
    toggle-position: right
    background: "#27ae60"  # Intense healing green
    logo: images/tds-logo-150px.png
    logo-alt: "Music-Soul-Love"
    title: false
    collapse-below: lg
    right:
    - text: "Albums"
      href: albums/index.qmd
    - text: "Emotional Journeys"
      href: emotional-journeys/index.qmd
    - text: "Research"
      href: research/index.qmd
    - text: "Therapy"
      href: therapy-techniques/index.qmd

  page-footer:
    left: "Copyright © 2025 thedatashrink™. All rights reserved."
    right:
      - icon: instagram
        href: https://instagram.com/thedatashrink
      - icon: twitter
        href: https://twitter.com/thedatashrink
      - icon: youtube
        href: https://youtube.com/@DoctorShrinkOfficial

format:
  html:
    theme: [tds-therapy.scss]
    css: tds-therapy.css
    toc: false

execute:
  freeze: auto